package finalhomework.tcl.com.finalhomework.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import finalhomework.tcl.com.finalhomework.pojo.BPay;
import finalhomework.tcl.com.finalhomework.pojo.Person;
import finalhomework.tcl.com.finalhomework.pojo.ShareBill;
import finalhomework.tcl.com.finalhomework.pojo.SortBill;
import finalhomework.tcl.com.finalhomework.pojo.TotalBill;

import finalhomework.tcl.com.finalhomework.greendao.BPayDao;
import finalhomework.tcl.com.finalhomework.greendao.PersonDao;
import finalhomework.tcl.com.finalhomework.greendao.ShareBillDao;
import finalhomework.tcl.com.finalhomework.greendao.SortBillDao;
import finalhomework.tcl.com.finalhomework.greendao.TotalBillDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig bPayDaoConfig;
    private final DaoConfig personDaoConfig;
    private final DaoConfig shareBillDaoConfig;
    private final DaoConfig sortBillDaoConfig;
    private final DaoConfig totalBillDaoConfig;

    private final BPayDao bPayDao;
    private final PersonDao personDao;
    private final ShareBillDao shareBillDao;
    private final SortBillDao sortBillDao;
    private final TotalBillDao totalBillDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        bPayDaoConfig = daoConfigMap.get(BPayDao.class).clone();
        bPayDaoConfig.initIdentityScope(type);

        personDaoConfig = daoConfigMap.get(PersonDao.class).clone();
        personDaoConfig.initIdentityScope(type);

        shareBillDaoConfig = daoConfigMap.get(ShareBillDao.class).clone();
        shareBillDaoConfig.initIdentityScope(type);

        sortBillDaoConfig = daoConfigMap.get(SortBillDao.class).clone();
        sortBillDaoConfig.initIdentityScope(type);

        totalBillDaoConfig = daoConfigMap.get(TotalBillDao.class).clone();
        totalBillDaoConfig.initIdentityScope(type);

        bPayDao = new BPayDao(bPayDaoConfig, this);
        personDao = new PersonDao(personDaoConfig, this);
        shareBillDao = new ShareBillDao(shareBillDaoConfig, this);
        sortBillDao = new SortBillDao(sortBillDaoConfig, this);
        totalBillDao = new TotalBillDao(totalBillDaoConfig, this);

        registerDao(BPay.class, bPayDao);
        registerDao(Person.class, personDao);
        registerDao(ShareBill.class, shareBillDao);
        registerDao(SortBill.class, sortBillDao);
        registerDao(TotalBill.class, totalBillDao);
    }
    
    public void clear() {
        bPayDaoConfig.clearIdentityScope();
        personDaoConfig.clearIdentityScope();
        shareBillDaoConfig.clearIdentityScope();
        sortBillDaoConfig.clearIdentityScope();
        totalBillDaoConfig.clearIdentityScope();
    }

    public BPayDao getBPayDao() {
        return bPayDao;
    }

    public PersonDao getPersonDao() {
        return personDao;
    }

    public ShareBillDao getShareBillDao() {
        return shareBillDao;
    }

    public SortBillDao getSortBillDao() {
        return sortBillDao;
    }

    public TotalBillDao getTotalBillDao() {
        return totalBillDao;
    }

}
